apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-arew
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0009-tenant/tkrw-pr712-0075-0009-app/devfile-sample-arew@sha256:c99d3f21b08c9e52a26a0ac6eec204da0aa647751df42c6a8fb33b31cb4ad63a
        name: my-nodejs
        resources: {}
status: {}
